name: Run API Request

on:
  workflow_dispatch:  # これにより、Actionsタブから手動でワークフローを実行できます
  push:
    branches:
      - main

jobs:
  api-request:
    runs-on: ubuntu-latest
    environment:
      name: production  # 環境名を指定してください

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub  # オプション: Docker Hubにログインが必要な場合
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
