version: '3.8'
services:
  api-request:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: |
      curl https://api.openai.com/v1/moderations \
        -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $OPENAI_API_KEY" \
        -d '{"input": "Sample text goes here"}'
